import type { ComponentDefinition } from '../types';
import { themeVar } from '../themes/themeTokens';

export const componentDefinitions: ComponentDefinition[] = [
  // ── Layout ───────────────────────────────────────────────────────────────
  {
    type: 'section',
    label: 'Section',
    category: 'Layout',
    icon: '▣',
    defaultProps: {},
    defaultStyles: { padding: '48px 24px', width: '100%' },
  },
  {
    type: 'container',
    label: 'Container',
    category: 'Layout',
    icon: '□',
    defaultProps: {},
    defaultStyles: {
      maxWidth: '1200px',
      margin: '0 auto',
      padding: '24px',
      minHeight: '120px',
      border: `1px dashed ${themeVar.border}`,
      backgroundColor: themeVar.surface,
      color: themeVar.text,
      tablet: { padding: '18px' },
      mobile: { padding: '12px' },
    },
  },
  {
    type: 'html-container',
    label: 'HTML Container',
    category: 'Layout',
    icon: '</>',
    defaultProps: { tag: 'div' },
    defaultStyles: {
      display: 'block',
      width: '100%',
      padding: '16px',
      tablet: { padding: '14px' },
      mobile: { padding: '10px' },
    },
  },
  {
    type: 'flex-row',
    label: 'Flex Row',
    category: 'Layout',
    icon: '⇔',
    defaultProps: {},
    defaultStyles: {
      display: 'flex',
      flexDirection: 'row',
      gap: '16px',
      alignItems: 'center',
      flexWrap: 'wrap',
      tablet: { gap: '14px' },
      mobile: { flexDirection: 'column', alignItems: 'stretch', gap: '12px' },
    },
  },
  {
    type: 'flex-col',
    label: 'Flex Column',
    category: 'Layout',
    icon: '⇕',
    defaultProps: {},
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      gap: '16px',
      tablet: { gap: '14px' },
      mobile: { gap: '12px' },
    },
  },
  {
    type: 'grid',
    label: 'Grid',
    category: 'Layout',
    icon: '⊞',
    defaultProps: { columns: 3 },
    defaultStyles: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: '24px',
      tablet: { gridTemplateColumns: 'repeat(2, 1fr)', gap: '16px' },
      mobile: { gridTemplateColumns: '1fr', gap: '12px' },
    },
  },
  {
    type: 'spacer',
    label: 'Spacer',
    category: 'Layout',
    icon: '↕',
    defaultProps: {},
    defaultStyles: { height: '48px', width: '100%' },
  },

  // ── Typography ────────────────────────────────────────────────────────────
  {
    type: 'heading',
    label: 'Heading',
    category: 'Typography',
    icon: 'H',
    defaultProps: { text: 'Your Heading Here', level: 2 },
    defaultStyles: { fontSize: '2.25rem', fontWeight: '700', lineHeight: '1.2', color: 'inherit' },
  },
  {
    type: 'paragraph',
    label: 'Paragraph',
    category: 'Typography',
    icon: 'P',
    defaultProps: { text: 'Add your paragraph text here. Click to edit.' },
    defaultStyles: { fontSize: '1rem', lineHeight: '1.6', color: 'inherit' },
  },
  {
    type: 'list',
    label: 'List',
    category: 'Typography',
    icon: '•',
    defaultProps: { ordered: false, items: ['First item', 'Second item', 'Third item'] },
    defaultStyles: { fontSize: '1rem', lineHeight: '1.6', color: 'inherit', paddingLeft: '1.25rem' },
  },
  {
    type: 'link',
    label: 'Link',
    category: 'Typography',
    icon: '↗',
    defaultProps: { text: 'Visit link', href: 'https://example.com', target: '_blank' },
    defaultStyles: { color: themeVar.primary, textDecoration: 'underline', cursor: 'pointer' },
  },
  {
    type: 'html-element',
    label: 'HTML Element',
    category: 'Typography',
    icon: '<>',
    defaultProps: { tag: 'span', text: 'Custom HTML element' },
    defaultStyles: { color: 'inherit' },
  },
  {
    type: 'label',
    label: 'Label',
    category: 'Typography',
    icon: 'L',
    defaultProps: { text: 'Label' },
    defaultStyles: { fontSize: '0.875rem', fontWeight: '500', color: 'inherit' },
  },
  {
    type: 'badge',
    label: 'Badge',
    category: 'Typography',
    icon: '◉',
    defaultProps: { text: 'New' },
    defaultStyles: {
      display: 'inline-flex',
      padding: '2px 10px',
      borderRadius: '9999px',
      fontSize: '0.75rem',
      fontWeight: '600',
      backgroundColor: themeVar.primary,
      color: themeVar.onPrimary,
    },
  },

  // ── Interactive ───────────────────────────────────────────────────────────
  {
    type: 'button',
    label: 'Button',
    category: 'Interactive',
    icon: '⬛',
    defaultProps: { text: 'Click Me', variant: 'primary' },
    defaultStyles: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '12px 28px',
      borderRadius: '8px',
      fontSize: '1rem',
      fontWeight: '600',
      backgroundColor: themeVar.primary,
      color: themeVar.onPrimary,
      cursor: 'pointer',
      border: 'none',
    },
  },
  {
    type: 'input',
    label: 'Input',
    category: 'Interactive',
    icon: '▭',
    defaultProps: { placeholder: 'Enter text...', type: 'text', name: 'field', ariaLabel: 'Text input' },
    defaultStyles: {
      padding: '10px 16px',
      borderRadius: '8px',
      border: `1px solid ${themeVar.border}`,
      fontSize: '1rem',
      backgroundColor: themeVar.surface,
      color: themeVar.text,
      width: '100%',
    },
  },
  {
    type: 'textarea',
    label: 'Textarea',
    category: 'Interactive',
    icon: '≣',
    defaultProps: {
      placeholder: 'Tell visitors more...',
      rows: 5,
      name: 'message',
      ariaLabel: 'Message field',
      value: '',
    },
    defaultStyles: {
      padding: '12px 16px',
      borderRadius: '10px',
      border: `1px solid ${themeVar.border}`,
      fontSize: '1rem',
      lineHeight: '1.6',
      backgroundColor: themeVar.surface,
      color: themeVar.text,
      width: '100%',
      minHeight: '140px',
    },
  },
  {
    type: 'select',
    label: 'Select',
    category: 'Interactive',
    icon: '▾',
    defaultProps: {
      name: 'selection',
      ariaLabel: 'Select an option',
      value: 'starter',
      options: ['Starter', 'Growth', 'Enterprise'],
    },
    defaultStyles: {
      padding: '10px 16px',
      borderRadius: '8px',
      border: `1px solid ${themeVar.border}`,
      fontSize: '1rem',
      backgroundColor: themeVar.surface,
      color: themeVar.text,
      width: '100%',
      appearance: 'none',
    },
  },
  {
    type: 'navbar',
    label: 'Navbar',
    category: 'Interactive',
    icon: '≡',
    defaultProps: { brand: 'My Site', links: ['Home', 'About', 'Contact'] },
    defaultStyles: {
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '16px 32px',
      backgroundColor: themeVar.surface,
      borderBottom: `1px solid ${themeVar.border}`,
      color: themeVar.text,
      gap: '12px',
      tablet: { padding: '14px 18px' },
      mobile: { padding: '10px 12px', justifyContent: 'flex-start' },
    },
  },

  // ── Media ─────────────────────────────────────────────────────────────────
  {
    type: 'image',
    label: 'Image',
    category: 'Media',
    icon: '🖼',
    defaultProps: { src: 'https://placehold.co/600x400', alt: 'Image', objectFit: 'cover' },
    defaultStyles: { width: '100%', borderRadius: '8px', display: 'block' },
  },
  {
    type: 'video',
    label: 'Video',
    category: 'Media',
    icon: '▶',
    defaultProps: { src: '', poster: '', controls: true },
    defaultStyles: { width: '100%', borderRadius: '8px' },
  },
  {
    type: 'icon',
    label: 'SVG Icon',
    category: 'Media',
    icon: '◇',
    defaultProps: { iconName: 'sparkles', size: 28, strokeWidth: 2, ariaLabel: 'Decorative icon' },
    defaultStyles: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: themeVar.primary,
    },
  },

  // ── Advanced ──────────────────────────────────────────────────────────────
  {
    type: 'hero',
    label: 'Hero Section',
    category: 'Advanced',
    icon: '★',
    defaultProps: {
      title: 'Build Modern Websites',
      subtitle: 'Design visually. Export real code.',
      ctaText: 'Get Started',
    },
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      textAlign: 'center',
      padding: '120px 24px',
      backgroundColor: themeVar.background,
      color: themeVar.text,
      tablet: { padding: '88px 20px' },
      mobile: { padding: '64px 16px' },
    },
  },
  {
    type: 'footer',
    label: 'Footer',
    category: 'Advanced',
    icon: '▁',
    defaultProps: { copyright: '© 2025 My Site. All rights reserved.' },
    defaultStyles: {
      padding: '32px 24px',
      textAlign: 'center',
      backgroundColor: themeVar.surface,
      borderTop: `1px solid ${themeVar.border}`,
      color: themeVar.textMuted,
      fontSize: '0.875rem',
      mobile: { padding: '24px 16px' },
    },
  },
  {
    type: 'feature-grid',
    label: 'Feature Grid',
    category: 'Advanced',
    icon: '⊞',
    defaultProps: {
      features: [
        { title: 'Fast', description: 'Built for speed.' },
        { title: 'Flexible', description: 'Customize anything.' },
        { title: 'Beautiful', description: 'Stunning by default.' },
      ],
    },
    defaultStyles: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: '24px',
      padding: '64px 24px',
      tablet: { gridTemplateColumns: 'repeat(2, 1fr)', gap: '18px', padding: '42px 18px' },
      mobile: { gridTemplateColumns: '1fr', gap: '14px', padding: '28px 14px' },
    },
  },
  {
    type: 'testimonial',
    label: 'Testimonial',
    category: 'Advanced',
    icon: '❝',
    defaultProps: {
      quote: 'This product changed my life.',
      author: 'Jane Doe',
      role: 'CEO, Example Co',
    },
    defaultStyles: {
      padding: '48px 32px',
      textAlign: 'center',
      borderRadius: '12px',
      backgroundColor: themeVar.surface,
      color: themeVar.text,
    },
  },
  {
    type: 'pricing-table',
    label: 'Pricing Table',
    category: 'Advanced',
    icon: '$',
    defaultProps: {
      plans: [
        { name: 'Starter', price: '$9/mo', features: ['5 Projects', 'Email Support', '1 GB Storage'], ctaText: 'Get Started' },
        { name: 'Pro', price: '$29/mo', features: ['Unlimited Projects', 'Priority Support', '50 GB Storage', 'Analytics'], ctaText: 'Get Started', highlighted: true },
        { name: 'Enterprise', price: 'Custom', features: ['Custom Integrations', 'Dedicated Support', 'Unlimited Storage'], ctaText: 'Contact Us' },
      ],
    },
    defaultStyles: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: '24px',
      padding: '64px 24px',
      tablet: { gridTemplateColumns: 'repeat(2, 1fr)', gap: '18px', padding: '42px 18px' },
      mobile: { gridTemplateColumns: '1fr', gap: '14px', padding: '28px 14px' },
    },
  },
  {
    type: 'faq',
    label: 'FAQ',
    category: 'Advanced',
    icon: '?',
    defaultProps: {
      questions: [
        { q: 'What is this product?', a: 'A powerful visual tool for building production-ready websites without writing code.' },
        { q: 'How does pricing work?', a: 'We offer flexible monthly and annual plans to fit teams of any size.' },
        { q: 'Do you offer a free trial?', a: 'Yes! Try it free for 14 days — no credit card required.' },
      ],
    },
    defaultStyles: {
      padding: '64px 24px',
      maxWidth: '800px',
      margin: '0 auto',
      tablet: { padding: '44px 18px' },
      mobile: { padding: '28px 14px' },
    },
  },
  {
    type: 'cta-banner',
    label: 'CTA Banner',
    category: 'Advanced',
    icon: '⚡',
    defaultProps: {
      eyebrow: 'Ready to launch? ',
      title: 'Build your site faster with visual editing',
      subtitle: 'Design your pages, tune styles, then export production-ready code in minutes.',
      primaryCta: 'Start Free',
      secondaryCta: 'See Demo',
    },
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      textAlign: 'center',
      gap: '12px',
      padding: '56px 28px',
      borderRadius: '16px',
      backgroundImage: themeVar.brandGradient,
      color: themeVar.onPrimary,
      margin: '40px auto',
      maxWidth: '980px',
      tablet: { padding: '42px 22px', margin: '24px auto' },
      mobile: { padding: '28px 16px', margin: '16px auto' },
    },
  },
  {
    type: 'stats-strip',
    label: 'Stats Strip',
    category: 'Advanced',
    icon: '▦',
    defaultProps: {
      stats: [
        { label: 'Active users', value: '120K+', helper: 'Across 42 countries' },
        { label: 'Uptime', value: '99.99%', helper: 'Last 12 months' },
        { label: 'Avg. load time', value: '0.9s', helper: 'Global edge delivery' },
        { label: 'Support score', value: '4.9/5', helper: 'From 18K reviews' },
      ],
    },
    defaultStyles: {
      display: 'grid',
      gridTemplateColumns: 'repeat(4, 1fr)',
      gap: '20px',
      padding: '48px 24px',
      backgroundColor: themeVar.surface,
      border: `1px solid ${themeVar.border}`,
      color: themeVar.text,
      borderRadius: '16px',
      margin: '40px auto',
      maxWidth: '1100px',
      tablet: { gridTemplateColumns: 'repeat(2, 1fr)', gap: '14px', padding: '28px 14px', margin: '24px auto' },
      mobile: { gridTemplateColumns: '1fr', gap: '10px', padding: '20px 12px', margin: '18px auto' },
    },
  },
  {
    type: 'tabs',
    label: 'Tabs',
    category: 'Advanced',
    icon: '☰',
    defaultProps: {
      items: [
        { label: 'Overview', content: 'A high-level overview of your product, outcomes, and value proposition.' },
        { label: 'Features', content: 'Highlight key features, integrations, and implementation details here.' },
        { label: 'Pricing', content: 'Share plan tiers, included features, and team scaling options.' },
      ],
      activeIndex: 0,
    },
    defaultStyles: {
      padding: '40px 24px',
      border: `1px solid ${themeVar.border}`,
      borderRadius: '14px',
      backgroundColor: themeVar.surface,
      color: themeVar.text,
      maxWidth: '900px',
      margin: '40px auto',
      tablet: { padding: '28px 18px', margin: '24px auto' },
      mobile: { padding: '20px 14px', margin: '16px auto' },
    },
  },
  {
    type: 'accordion',
    label: 'Accordion',
    category: 'Advanced',
    icon: '⋮',
    defaultProps: {
      items: [
        { title: 'How does billing work?', content: 'Billing is monthly or annual, with prorated upgrades and downgrades.' },
        { title: 'Can I invite my team?', content: 'Yes, team seats and role-based permissions are included in Pro and above.' },
        { title: 'Do you offer migration help?', content: 'We provide migration guides, starter templates, and optional support sessions.' },
      ],
      openIndex: 0,
    },
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      gap: '10px',
      padding: '32px 20px',
      maxWidth: '860px',
      margin: '40px auto',
      mobile: { padding: '24px 14px', margin: '16px auto' },
    },
  },
  {
    type: 'timeline',
    label: 'Timeline',
    category: 'Advanced',
    icon: '⟡',
    defaultProps: {
      items: [
        { date: 'Week 1', title: 'Discovery', description: 'Define goals, success metrics, and technical constraints.' },
        { date: 'Week 2', title: 'Prototype', description: 'Build interactive prototypes and validate flows with stakeholders.' },
        { date: 'Week 3', title: 'Implementation', description: 'Ship the first production-ready iteration and monitor quality.' },
      ],
    },
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      gap: '18px',
      padding: '36px 24px',
      borderLeft: `2px solid ${themeVar.border}`,
      color: themeVar.text,
      margin: '40px auto',
      maxWidth: '860px',
      mobile: { gap: '14px', padding: '26px 14px', margin: '16px auto' },
    },
  },
  {
    type: 'carousel',
    label: 'Carousel',
    category: 'Advanced',
    icon: '◁',
    defaultProps: {
      activeIndex: 0,
      slides: [
        { title: 'First slide', description: 'Showcase a hero message or product highlight.', image: 'https://placehold.co/1200x600/0f172a/f8fafc?text=Slide+1' },
        { title: 'Second slide', description: 'Use this for testimonials, features, or promotions.', image: 'https://placehold.co/1200x600/1e293b/f8fafc?text=Slide+2' },
        { title: 'Third slide', description: 'Add clear calls-to-action with supporting visuals.', image: 'https://placehold.co/1200x600/334155/f8fafc?text=Slide+3' },
      ],
    },
    defaultStyles: {
      position: 'relative',
      width: '100%',
      maxWidth: '980px',
      margin: '40px auto',
      borderRadius: '14px',
      overflow: 'hidden',
      border: `1px solid ${themeVar.border}`,
      backgroundColor: themeVar.surface,
      color: themeVar.text,
      mobile: { margin: '16px auto' },
    },
  },
  {
    type: 'comparison-table',
    label: 'Comparison Table',
    category: 'Advanced',
    icon: '▤',
    defaultProps: {
      columns: ['Starter', 'Pro', 'Enterprise'],
      rows: [
        { feature: 'Projects', values: ['5', 'Unlimited', 'Unlimited'] },
        { feature: 'Team members', values: ['3', '20', 'Unlimited'] },
        { feature: 'Priority support', values: ['No', 'Yes', 'Yes'] },
      ],
    },
    defaultStyles: {
      width: '100%',
      maxWidth: '980px',
      margin: '40px auto',
      border: `1px solid ${themeVar.border}`,
      borderRadius: '14px',
      overflow: 'hidden',
      backgroundColor: themeVar.surface,
      color: themeVar.text,
    },
  },
  {
    type: 'team-grid',
    label: 'Team Grid',
    category: 'Advanced',
    icon: '👥',
    defaultProps: {
      members: [
        { name: 'Avery Chen', role: 'Founder & CEO', bio: 'Vision, product strategy, and customer success.', avatar: 'https://placehold.co/300x300/1e293b/f8fafc?text=AC' },
        { name: 'Jordan Patel', role: 'Design Lead', bio: 'Design systems, UX research, and prototyping.', avatar: 'https://placehold.co/300x300/334155/f8fafc?text=JP' },
        { name: 'Riley Morgan', role: 'Engineering Lead', bio: 'Platform architecture and frontend performance.', avatar: 'https://placehold.co/300x300/0f172a/f8fafc?text=RM' },
      ],
    },
    defaultStyles: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: '20px',
      maxWidth: '980px',
      margin: '40px auto',
      padding: '12px',
      tablet: { gridTemplateColumns: 'repeat(2, 1fr)', gap: '14px', margin: '24px auto', padding: '10px' },
      mobile: { gridTemplateColumns: '1fr', gap: '10px', margin: '16px auto', padding: '8px' },
    },
  },
];

export const componentsByCategory = componentDefinitions.reduce<
  Record<string, ComponentDefinition[]>
>((acc, def) => {
  if (!acc[def.category]) acc[def.category] = [];
  acc[def.category].push(def);
  return acc;
}, {});
